export const animals = [
  'Blue ring angelfish',
  'Annularis angelfish',
  'Arabian angelfish',
  'Asfur angelfish',
  'Bellus angelfish',
  'Blue angelfish',
  'Bluespotted angelfish',
  'Blueface angelfish',
  'Cortez angelfish',
  'Emperor angelfish',
  'French angelfish',
  'Gray angelfish',
  'Griffis angelfish',
  'Half-moon angelfish',
  'Yellow bar angelfish',
  'Koran angelfish',
  'Majestic angelfish',
  'Blue girdled angelfish',
  'Passer angelfish',
  'King angelfish',
  'Personifer angelfish',
  'Queensland yellowtail angelfish',
  'Queen angelfish',
  'Rock beauty',
  'Royal angelfish',
  'Scribbled angelfish',
  'Japanese swallow angelfish',
  'Yellowtail angelfish',
  'Barred angelfish',
  'Bicolor angelfish',
  'Blue Velvet Angelfish',
  'Brazilian flameback angelfish',
  'Coral beauty angelfish',
  'Cherubfish',
  'Pygmy angelfish',
  'Eibli angelfish',
  'Flame angelfish',
  'Half-black angelfish',
  "Herald's angelfish",
  'Keyhole angelfish',
  'Lemonpeel angelfish',
  'Multicolor angelfish',
  'Orange-back angelfish',
  'Pacific pygmy angelfish',
  "Potter's angelfish",
  'Rusty angelfish',
  'Venustus angelfish',
  "Bartlett's anthias",
  'Bicolor anthias',
  "Cooper's anthias",
  'Diadem anthias',
  'Orangehead anthias',
  'Redbar anthias',
  'Lyretail anthias',
  'Sea Goldie',
  'Squareback anthias',
  'Stocky anthias',
  'Threadfin anthias',
  'African grouper',
  'Vermillion seabass',
  'Blacktip grouper',
  'Blue and Yellow grouper',
  'Blue dot grouper',
  'Blue line grouper',
  'Chalk bass',
  'Coney grouper',
  'Golden grouper',
  'Golden stripe soapfish',
  'Harlequin bass',
  'Leaflip grouper',
  'Marine beta',
  'Miniatus grouper',
  'Vermillion seabass',
  'Orange spot grouper',
  'Panther grouper',
  'Painted comber',
  'Polleni grouper',
  'Red flag grouper',
  'Lyretail grouper',
  'Saddle grouper',
  'Spotted grouper',
  'Strawberry grouper',
  'V tail grouper',
  'Black cap gramma',
  'Blue assessor',
  'Royal gramma',
  'Brazilian gramma',
  'Yellow assessor',
  'Orbiculate batfish',
  'Dusky batfish',
  'Teira batfish',
  'Spinyhead blenny',
  'Bicolor blenny',
  'Black combtooth blenny',
  'Blackline fang blenny',
  'Black sailfin blenny',
  'Blue & gold blenny',
  'Bundoon blenny',
  'Canary fang blenny',
  'Diamond blenny',
  'Ember blenny',
  'Lawnmower blenny',
  'Linear blenny',
  'Midas blenny',
  'Molly Miller blenny',
  'One spot blenny',
  'Red lip blenny',
  'Red Sea mimic blenny',
  'Sailfin blenny',
  'Segmented sailfin blenny',
  'Starry blenny',
  'Striped blenny',
  'Tail spot blenny',
  'Two-spot blenny',
  'Engineer goby',
  'Golden puffer',
  'Hawaiian blue puffer',
  'Hawaiian saddle puffer',
  'Hawaiian spotted puffer',
  'Helmet cowfish',
  'Immaculate puffer',
  'Longhorn cowfish',
  'Scribbled boxfish',
  'Dogface pufferfish',
  'Map puffer',
  'Porcupine pufferfish',
  'Spotfin porcupinefish',
  'Sharpnose pufferfish',
  'Star puffer',
  'Stars and stripes puffer',
  'Striped dogface puffer',
  'Valentini pufferfish',
  'Whitebelly puffer',
  'Yellow boxfish',
  'Copperband butterflyfish',
  'Schooling bannerfish',
  'Longnose butterflyfish',
  'Raccoon butterflyfish',
  'Redback butterflyfish',
  "Merten's butterflyfish",
  'Teardrop butterflyfish',
  'Latticed butterflyfish',
  'Pacific double saddle butterflyfish',
  'Sickle butterflyfish',
  'Auriga butterflyfish',
  "Tinker's butterflyfish",
  'Masked butterflyfish',
  'Reef butterflyfish',
  'Four-eyed butterflyfish',
  'Banded butterflyfish',
  'Saddleback butterflyfish',
  'Fragile cardinalfish',
  'Banggai cardinal',
  'Blackstripe cardinalfish',
  'Bluebarred cardinalfish',
  'Bluestreak cardinalfish',
  'Flamefish',
  'Frostfin cardinalfish',
  "Gilbert's cardinalfish",
  'Girdled cardinalfish',
  'Orange-striped cardinalfish',
  'Orbic cardinalfish',
  'Pajama cardinalfish',
  'Ochre-striped cardinalfish',
  'Ringtailed cardinalfish',
  'Ambon chromis',
  'Barrier reef chromis',
  'Black and gold chromis',
  'Black bar chromis',
  'Blue chromis',
  'Damselfish',
  'Green chromis',
  'Half and half chromis',
  'Limbaughi chromis',
  'Lined chromis',
  'Paletail chromis',
  'Black-axil chromis',
  'Spiny chromis',
  'Sunshine chromis',
  'Yellowspotted chromis',
  'Black and white chromis',
  'Cinnamon anemonefish',
  'Clarkii anemonefish',
  'Ocellaris',
  'Maroon clownfish',
  'True Percula',
  'Pink skunk anemonefish',
  'Tomato clownfish',
  'Saddleback anemonefish',
  'Sebae anemonefish',
  'Ambon damsel',
  'Azure damsel',
  'Black and gold damsel',
  'Blackmargined damsel',
  'Blue damsel',
  'Orangetail damsel',
  'Blue and gold damsel',
  'Blue velvet damsel',
  'Blueback damsel',
  'Blueline demoiselle',
  'YYellowfin demoiselle',
  'Bluefin damsel',
  'Caerulean damsel',
  'Canary deep water damsel',
  'Cloudy damsel',
  "Cross' damsel",
  'Domino damsel',
  'Fiji blue devil damsel',
  'Four stripe damsel',
  'Garibaldi damsel',
  'Honey head damsel',
  'Jewel damsel',
  'King demoiselle',
  'Lemon damsel',
  'Longfin gregory',
  'Marginated damsel',
  'Neon damsel',
  'Ocellate damsel',
  'Pavo damsel',
  'Pink Smith damsel',
  "Rolland's demoiselle",
  'Sergeant major damsel',
  'Speckled damsel',
  "Springer's damsel",
  "Stark's damsel",
  'Talbots damsel',
  'Three stripe damsel',
  'Three Spot damsel',
  'Tuxedo damsel',
  'Two stripe damsel',
  'Yellow damsel',
  'Yellowbelly damsel',
  'Yellowtail damsel',
  'Yellowtail demoiselle',
  'Blue gudgeon dartfish',
  'Fire fish',
  'Purple fire fish',
  'Scissortail dartfish',
  'Zebra barred dartfish',
  'Mandarinfish',
  'Starry dragonet',
  'Ocellated dragonet',
  'Spotted mandarin',
  'Banded snake eel',
  'Banded eel',
  'Black edge moray eel',
  'Blue ribbon eel',
  'Bblack ribbon eel',
  'Chainlink moray eel',
  'Dragon moray eel',
  'Golden dwarf eel',
  'Golden moray eel',
  'Green moray eel',
  'Jeweled moray eel',
  'Kidako moray eel',
  'Peppered moray',
  'Snowflake eel',
  'Spotted garden-eel',
  'Spotted Snake eel',
  'Tessalata eel',
  'Oor laced moray',
  'Yellowhead moray eel',
  'Yellow mouth moray eel',
  'Whitemouth moray eel',
  'Carpet eel-blenny',
  'Zebra moray',
  'Clown filefish',
  'Colored filefish',
  'Fantail orange filefish',
  'Horseshoe filefish',
  'Japanese filefish',
  'Mimic filefish',
  'Orangespotted filefish',
  'Tassle filefish',
  'Peacock flounder',
  'Flowery (Indo-Pacific peacock) flounder',
  'Banded sole',
  'Longlure frogfish',
  'Giant anglerfish',
  'Sargassum frogfish',
  'Striated frogfish',
  'Wartskin frogfish',
  'Bicolor goatfish',
  'Goldsaddle goatfish',
  'Manybar goatfish',
  'Yellow back goatfish',
  'Black barred convict goby',
  'Black clown goby',
  'Bluespotted watchman goby',
  'Catalina goby',
  'Cave transparent goby',
  'Citron clown goby',
  'Court jester goby',
  'Diagonal bar prawn goby',
  'Diamond watchman goby',
  'Dracula goby',
  'Gold neon eviota goby',
  'Green banded goby',
  'Green clown goby',
  "Hector's goby",
  'Hi fin red banded goby',
  'Neon goby',
  'Orange marked goby',
  'Orange spotted goby',
  'Orange stripe prawn goby',
  'Pinkspotted shrimp goby',
  'Pinkbar goby',
  'Red head goby',
  'Red striped goby',
  'Sleeper banded goby',
  'Sleeper blue dot goby',
  'Sleeper gold head goby',
  'Sleeper railway glider goby',
  'Sleeper striped goby',
  'Steinitz goby',
  'Tangaroa goby',
  'Tiger watchman goby',
  'Two spot goby',
  'Violet goby',
  "Wheeler's watchman goby",
  'Yellow watchman goby',
  'Yasha goby',
  'Yellow clown goby',
  'Yellow priolepis goby',
  'Yellow stripe clingfish',
  'Crescent banded grunt',
  'Dogfish prientalis',
  'Painted sweetlips',
  'Porkfish',
  'Spotted sweetlips',
  'Striped sweetlips',
  'Twostriped sweetlips',
  'Barred hamlet',
  'Black hamlet',
  'Blue hamlet',
  'Butter hamlet',
  'Golden hamlet',
  'Indigo hamlet',
  'Shy hamlet',
  'Arc eye hawkfish',
  'Blood red hawkfish',
  'Coral hawkfish',
  "Falco's hawkfish",
  'Flame hawkfish',
  'Freckled hawkfish',
  'Golden hawkfish',
  'Longnose hawkfish',
  'Lyretail hawkfish',
  'Redspotted hawkfish',
  'Spotted hawkfish',
  'Whitespot hawkfish',
  'Yellow hawkfish',
  'Coral hogfish',
  'Cuban hogfish',
  'Hawaiian hogfish',
  'Red diana hogfish',
  'Spanish hogfish',
  'Twin spot hogfish',
  'Moorish idol',
  'Pilot fish',
  'Golden trevally',
  'Indian threadfin',
  'Threadfin lookdown',
  'Black cap jawfish',
  'Blue dot jawfish',
  'Dusky jawfish',
  'Yellowhead jawfish',
  'Antenneta lionfish',
  'Blackfoot lionfish',
  'Devil lionfish',
  'Fu Man Chu lionfish',
  'Fuzzy dwarf lionfish',
  'Green lionfish',
  'Radiata lionfish',
  "Russell's lionfish",
  'Volitan lionfish',
  'Zebra lionfish',
  'Bicolor parrotfish',
  'Princess parrotfish',
  'Banded pipefish',
  'Dragonface pipefish',
  "Janss' pipefish",
  'Yellow multibanded pipefish',
  "Allen's dottyback",
  'Australian multicolor pseudochromis',
  'Bicolor pseudochromis',
  'Blue flavivertex pseudochromis',
  'Bluelined dottyback',
  'Brown dottyback',
  'Yellow pseudochromis',
  'Cherry dottyback',
  'Dilectus dottyback',
  'Dusky dottyback',
  'Elongate dottyback',
  'Firetail dottyback',
  'Fridmani pseudochromis',
  'Orchid dottyback',
  'Longfin dottyback',
  'Lyretail dottyback',
  'Neon pseudochromis',
  'Arabian dottyback or neon dottyback',
  'Oblique-lined dottyback',
  'Orangetail dottyback',
  'Purple stripe pseudochromis',
  'Diadema basslet',
  'Red dottyback',
  'Sailfin pseudochromis',
  'Splendid pseudochromis',
  'Springeri pseudochromis',
  'Striped dottyback',
  'Strawberry pseudochromis',
  'Purple pseudochromis',
  'Twolined dottyback',
  'Bicolor Foxface',
  'Blue-Lined Rabbitfish',
  'Foxface',
  'Magnificent foxface',
  'One Spot Foxface',
  'Yellow Blotch Rabbitfish',
  'Round stingray',
  'Cortez round stingray',
  'Bullseye round stingray',
  'Leopard round stingray',
  'Yellow stingray',
  'Chilean round ray',
  'Bluespotted ribbontail ray',
  'Bluespotted stingray',
  'Southern stingray',
  'Atlantic stingray',
  'Bluntnose Stingray',
  'Reticulated whiptail ray',
  'Red stingray',
  'Cowtail stingray',
  'Common stingaree',
  'Striped stingaree',
  'Spotted stingaree',
  'Shovelnose guitarfish',
  'Atlantic guitarfish',
  'Speckled guitarfish',
  'Eastern shovelnose ray',
  'Giant shovelnose ray',
  'Bowmouth guitarfish',
  'Eastern fiddler ray',
  'Thornback ray',
  'Shortnose guitarfish',
  'Banded guitarfish',
  'Southern banded guitarfish',
  'Leopard torpedo ray',
  'Marbled electric ray',
  'Marbled electric ray',
  'Bullseye electric ray',
  'Lesser electric ray',
  'Brown numbfish',
  'Unknown electric ray',
  'Elat electric ray',
  'Spiny butterfly ray',
  'Smooth butterfly ray',
  'California butterfly ray',
  'Bat ray',
  'Bullnose eagle ray',
  'Southern eagle ray',
  'Spotted eagle ray',
  'Cownose ray',
  'Ambon scorpionfish',
  'Decoy scorpionfish',
  "Eschmeyer's scorpionfish",
  'Flasher scorpionfish',
  'Lacey scorpionfish',
  'Leaf scorpionfish',
  'Mozambique scorpionfish',
  'Papuan scorpionfish',
  "Poss's scorpionfish",
  'Rogue scorpion',
  'Sea goblin',
  'Stone fish',
  'Weedy scorpionfish',
  'Yellowspotted scorpionfish',
  'Brazilian seahorse',
  'Spotted seahorse',
  'Great seahorse',
  'Pot-bellied seahorse',
  'Pygmy seahorse',
  'Short-snouted seahorse',
  'Tiger tail seahorse',
  'Lined Seahorse',
  "White's Seahorse",
  'Dwarf Seahorse',
  'Thorny Seahorse',
  'Big eye soldierfish',
  'Blackbar soldierfish',
  'Glass eye squirrelfish',
  'Popeye catalufa soldierfish',
  'Scarlet squirrelfish',
  'Striped squirrelfish',
  'Whitespotted bamboo shark',
  'Brownbanded bamboo shark',
  'Epaulette shark',
  'Horn shark',
  'Port Jackson shark',
  'Coral catshark',
  'Marbled catshark',
  'Nurse shark',
  'Zebra shark',
  'Leopard shark',
  'Banded houndshark',
  'Gray smooth-hound',
  'Brown smooth-hound',
  'Tasselled wobbegong',
  'Japanese wobbegong',
  'Ornate wobbegong',
  'Spotted wobbegong',
  'Northern wobbegong',
  'Blacktip reef shark',
  'Whitetip reef shark',
  'Bonnethead shark',
  'Shark egg case',
  'Black snapper',
  'Black and white snapper',
  'Emperor snapper',
  'Threadfin snapper',
  'Yellowback fusilier',
  'Yellow-Banded Snapper',
  'Hussar Emperor Snapper',
  'Achilles tang',
  'Atlantic blue tang',
  'Blue eyed tang',
  'Blue lined surgeonfish',
  'Bristletooth tang',
  'Chevron tang',
  'Clown tang',
  'Convict tang',
  'Desjardini tang',
  'Doctorfish',
  'Dussumieri tang',
  'Eibli mimic tang',
  'Gold rim tang',
  'Regal / Hippo tang',
  'Kole tang',
  'Lavender tang',
  'Lopezi tang',
  'Mimic tang',
  'Chocolate tang',
  'Naso tang',
  'Bblonde naso tang',
  'Orange shoulder tang',
  'Powder blue tang',
  'Powder brown tang',
  'Purple tang',
  'Sailfin tang',
  'Scopas tang',
  'Sohal tang',
  'Tennent tang',
  "Thompson's surgeonfish",
  'Tomini tang',
  'Unicorn tang',
  'Vlamingi tang',
  'White freckled surgeon',
  'Yellow tang',
  'Yellowfin surgeon',
  'Blue-headed tilefish',
  'Purple tilefish',
  'Yellow tilefish',
  'Redlined tilefish',
  'Assasi trigger',
  'Blue jaw trigger',
  'Blue throat trigger',
  'Blue line trigger',
  'Bursa trigger',
  'Clown trigger',
  'Crosshatch trigger',
  'Goldenback trigger',
  'Golden heart trigger',
  'Halfmoon trigger',
  'Hawaiian black trigger',
  'Lei trigger',
  'Indian black trigger',
  'Niger trigger',
  'Picasso trigger',
  'Pinktail trigger',
  'Queen trigger',
  'Rectangular trigger',
  'Sargassum trigger',
  'Starry trigger',
  'Titan trigger',
  'Undulated trigger',
  'Whitetail trigger',
  'Banana wrasse',
  'Bicolor cleaner wrasse',
  'Bird wrasse',
  'Bluehead wrasse',
  'Bluestreak cleaner wrasse',
  "Carpenter's flasher wrasse",
  'Cheeklined maori wrasse',
  'Christmas wrasse',
  'Cortez rainbow wrasse',
  'Dragon wrasse',
  'Eight line wrasse',
  'Exquisite fairy wrasse',
  'Fine-spotted fairy wrasse',
  'Flame wrasse',
  'Formosa wrasse',
  'Four line wrasse',
  'Goldbar wrasse',
  'Greenback fairy wrasse',
  'Harlequin tusk',
  'Hawaiian cleaner wrasse',
  "Hoeven's wrasse",
  'Jansen saddle wrasse',
  "Labout's fairy wrasse",
  'Leopard wrasse',
  'Lineatus fairy wrasse',
  'Longfin fairy wrasse',
  'Lyretail wrasse/Moon wrasse',
  'Marble wrasse',
  "McCosker's flasher wrasse",
  "Multicolor lubbock's wrasse",
  'Multicolor velvet wrasse',
  'Mystery wrasse',
  'Orange-back fairy wrasse',
  'Pastel-green wrasse',
  'Pinkface wrasse',
  "Potter's wrasse",
  'Red coris wrasse',
  'Red-head fairy wrasse',
  'Red velvet wrasse',
  'Scarlet pin stripe wrasse',
  'Six line wrasse',
  'Radiant wrasse',
  'Rhomboid fairy wrasse',
  'Whip fin fairy wrasse',
  'Yellow wrasse',
  'Yellow & purple wrasse',
  'Yellowband wrasse',
  'Yellow fin fairy wrasse',
  'Yellow-flanked fairy wrasse',
];

export const adjectives = [
  'Aristotelian',
  'Arthurian',
  'Bohemian',
  'Brethren',
  'Mosaic',
  'Oceanic',
  'Proctor',
  'Terran',
  'Tudor',
  'abroad',
  'absorbing',
  'abstract',
  'academic',
  'accelerated',
  'accented',
  'accountant',
  'acquainted',
  'acute',
  'addicting',
  'addictive',
  'adjustable',
  'admired',
  'adult',
  'adverse',
  'advised',
  'aerosol',
  'afraid',
  'aggravated',
  'aggressive',
  'agreeable',
  'alienate',
  'aligned',
  'all-round',
  'alleged',
  'almond',
  'alright',
  'altruistic',
  'ambient',
  'ambivalent',
  'amiable',
  'amino',
  'amorphous',
  'amused',
  'anatomical',
  'ancestral',
  'angelic',
  'angrier',
  'answerable',
  'antiquarian',
  'antiretroviral',
  'appellate',
  'applicable',
  'apportioned',
  'approachable',
  'appropriated',
  'archer',
  'aroused',
  'arrested',
  'assertive',
  'assigned',
  'athletic',
  'atrocious',
  'attained',
  'authoritarian',
  'autobiographical',
  'avaricious',
  'avocado',
  'awake',
  'awsome',
  'backstage',
  'backwoods',
  'balding',
  'bandaged',
  'banded',
  'banned',
  'barreled',
  'battle',
  'beaten',
  'begotten',
  'beguiled',
  'bellied',
  'belted',
  'beneficent',
  'besieged',
  'betting',
  'big-money',
  'biggest',
  'biochemical',
  'bipolar',
  'blackened',
  'blame',
  'blessed',
  'blindfolded',
  'bloat',
  'blocked',
  'blooded',
  'blue-collar',
  'blushing',
  'boastful',
  'bolder',
  'bolstered',
  'bonnie',
  'bored',
  'boundary',
  'bounded',
  'bounding',
  'branched',
  'brawling',
  'brazen',
  'breeding',
  'bridged',
  'brimming',
  'brimstone',
  'broadest',
  'broiled',
  'broker',
  'bronze',
  'bruising',
  'buffy',
  'bullied',
  'bungling',
  'burial',
  'buttery',
  'candied',
  'canonical',
  'cantankerous',
  'cardinal',
  'carefree',
  'caretaker',
  'casual',
  'cathartic',
  'causal',
  'chapel',
  'characterized',
  'charcoal',
  'cheeky',
  'cherished',
  'chipotle',
  'chirping',
  'chivalrous',
  'circumstantial',
  'civic',
  'civil',
  'civilised',
  'clanking',
  'clapping',
  'claptrap',
  'classless',
  'cleansed',
  'cleric',
  'cloistered',
  'codified',
  'colloquial',
  'colour',
  'combat',
  'combined',
  'comely',
  'commissioned',
  'commonplace',
  'commuter',
  'commuting',
  'comparable',
  'complementary',
  'compromising',
  'conceding',
  'concentrated',
  'conceptual',
  'conditioned',
  'confederate',
  'confident',
  'confidential',
  'confining',
  'confuse',
  'congressional',
  'consequential',
  'conservative',
  'constituent',
  'contaminated',
  'contemporaneous',
  'contraceptive',
  'convertible',
  'convex',
  'cooked',
  'coronary',
  'corporatist',
  'correlated',
  'corroborated',
  'cosmic',
  'cover',
  'crash',
  'crypto',
  'culminate',
  'cushioned',
  'dandy',
  'dashing',
  'dazzled',
  'decreased',
  'decrepit',
  'dedicated',
  'defaced',
  'defective',
  'defenseless',
  'deluded',
  'deodorant',
  'departed',
  'depress',
  'designing',
  'despairing',
  'destitute',
  'detective',
  'determined',
  'devastating',
  'deviant',
  'devilish',
  'devoted',
  'diagonal',
  'dictated',
  'didactic',
  'differentiated',
  'diffused',
  'dirtier',
  'disabling',
  'disconnected',
  'discovered',
  'disdainful',
  'diseased',
  'disfigured',
  'disheartened',
  'disheveled',
  'disillusioned',
  'disparate',
  'dissident',
  'doable',
  'doctrinal',
  'doing',
  'dotted',
  'double-blind',
  'downbeat',
  'dozen',
  'draining',
  'draught',
  'dread',
  'dried',
  'dropped',
  'dulled',
  'duplicate',
  'eaten',
  'echoing',
  'economical',
  'elaborated',
  'elastic',
  'elective',
  'electoral',
  'elven',
  'embryo',
  'emerald',
  'emergency',
  'emissary',
  'emotional',
  'employed',
  'enamel',
  'encased',
  'encrusted',
  'endangered',
  'engraved',
  'engrossing',
  'enlarged',
  'enlisted',
  'enlivened',
  'ensconced',
  'entangled',
  'enthralling',
  'entire',
  'envious',
  'eradicated',
  'eroded',
  'esoteric',
  'essential',
  'evaporated',
  'ever-present',
  'evergreen',
  'everlasting',
  'exacting',
  'exasperated',
  'excess',
  'exciting',
  'executable',
  'existent',
  'exonerated',
  'exorbitant',
  'exponential',
  'export',
  'extraordinary',
  'exultant',
  'exulting',
  'facsimile',
  'fading',
  'fainter',
  'faith-based',
  'fallacious',
  'faltering',
  'famous',
  'fancier',
  'fast-growing',
  'fated',
  'favourable',
  'fearless',
  'feathered',
  'fellow',
  'fermented',
  'ferocious',
  'fiddling',
  'filling',
  'firmer',
  'fitted',
  'flammable',
  'flawed',
  'fledgling',
  'fleshy',
  'flexible',
  'flickering',
  'floral',
  'flowering',
  'flowing',
  'foggy',
  'folic',
  'foolhardy',
  'foolish',
  'footy',
  'forehand',
  'forked',
  'formative',
  'formulaic',
  'foul-mouthed',
  'fractional',
  'fragrant',
  'fraudulent',
  'freakish',
  'freckled',
  'freelance',
  'freight',
  'fresh',
  'fretted',
  'frugal',
  'fulfilling',
  'fuming',
  'funded',
  'funny',
  'garbled',
  'gathered',
  'geologic',
  'geometric',
  'gibberish',
  'gilded',
  'ginger',
  'glare',
  'glaring',
  'gleaming',
  'glorified',
  'glorious',
  'goalless',
  'gold-plated',
  'goody',
  'grammatical',
  'grande',
  'grateful',
  'gratuitous',
  'graven',
  'greener',
  'grinding',
  'grizzly',
  'groaning',
  'grudging',
  'guaranteed',
  'gusty',
  'half-breed',
  'hand-held',
  'handheld',
  'hands-off',
  'hard-pressed',
  'harlot',
  'healing',
  'healthier',
  'healthiest',
  'heart',
  'heart-shaped',
  'heathen',
  'hedonistic',
  'heralded',
  'herbal',
  'high-density',
  'high-performance',
  'high-res',
  'high-yield',
  'hissy',
  'hitless',
  'holiness',
  'homesick',
  'honorable',
  'hooded',
  'hopeless',
  'horrendous',
  'horrible',
  'hot-button',
  'huddled',
  'human',
  'humbling',
  'humid',
  'humiliating',
  'hypnotized',
  'idealistic',
  'idiosyncratic',
  'ignited',
  'illustrated',
  'illustrative',
  'imitated',
  'immense',
  'immersive',
  'immigrant',
  'immoral',
  'impassive',
  'impressionable',
  'improbable',
  'impulsive',
  'in-between',
  'in-flight',
  'inattentive',
  'inbound',
  'inbounds',
  'incalculable',
  'incomprehensible',
  'indefatigable',
  'indigo',
  'indiscriminate',
  'indomitable',
  'inert',
  'inflate',
  'inform',
  'inheriting',
  'injured',
  'injurious',
  'inking',
  'inoffensive',
  'insane',
  'insensible',
  'insidious',
  'insincere',
  'insistent',
  'insolent',
  'insufferable',
  'intemperate',
  'interdependent',
  'interesting',
  'interfering',
  'intern',
  'interpreted',
  'intersecting',
  'intolerable',
  'intolerant',
  'intuitive',
  'irresolute',
  'irritate',
  'jealous',
  'jerking',
  'joining',
  'joint',
  'journalistic',
  'joyful',
  'keyed',
  'knowing',
  'lacklustre',
  'laden',
  'lagging',
  'lamented',
  'laughable',
  'layered',
  'leather',
  'leathern',
  'leery',
  'left-footed',
  'legible',
  'leisure',
  'lessening',
  'liberating',
  'life-size',
  'lifted',
  'lightest',
  'limitless',
  'listening',
  'literary',
  'liver',
  'livid',
  'lobster',
  'locked',
  'long-held',
  'long-lasting',
  'long-running',
  'long-suffering',
  'loudest',
  'loveliest',
  'low-budget',
  'low-carb',
  'lowering',
  'lucid',
  'luckless',
  'lusty',
  'luxurious',
  'magazine',
  'maniac',
  'manmade',
  'maroon',
  'mastered',
  'mated',
  'material',
  'materialistic',
  'meaningful',
  'measuring',
  'mediaeval',
  'medical',
  'meditated',
  'medley',
  'melodic',
  'memorable',
  'memorial',
  'metabolic',
  'metallic',
  'metallurgical',
  'metering',
  'midair',
  'midterm',
  'midway',
  'mighty',
  'migrating',
  'mind-blowing',
  'mind-boggling',
  'minor',
  'mirrored',
  'misguided',
  'misshapen',
  'mitigated',
  'mixed',
  'modernized',
  'molecular',
  'monarch',
  'monastic',
  'morbid',
  'motley',
  'motorized',
  'mounted',
  'multi-million',
  'multidisciplinary',
  'muscled',
  'muscular',
  'muted',
  'mysterious',
  'mythic',
  'nail-biting',
  'natural',
  'nauseous',
  'negative',
  'networked',
  'neurological',
  'neutered',
  'newest',
  'night',
  'nitrous',
  'no-fly',
  'noncommercial',
  'nonsense',
  'north',
  'nuanced',
  'occurring',
  'offensive',
  'oldest',
  'oncoming',
  'one-eyed',
  'one-year',
  'onstage',
  'onward',
  'opaque',
  'open-ended',
  'operating',
  'opportunist',
  'opposing',
  'opt-in',
  'ordinate',
  'outdone',
  'outlaw',
  'outsized',
  'overboard',
  'overheated',
  'oversize',
  'overworked',
  'oyster',
  'paced',
  'panting',
  'paralyzed',
  'paramount',
  'parental',
  'parted',
  'partisan',
  'passive',
  'pastel',
  'patriot',
  'peacekeeping',
  'pedestrian',
  'peevish',
  'penal',
  'penned',
  'pensive',
  'perceptual',
  'perky',
  'permissible',
  'pernicious',
  'perpetuate',
  'perplexed',
  'pervasive',
  'petrochemical',
  'philosophical',
  'picturesque',
  'pillaged',
  'piped',
  'piquant',
  'pitching',
  'plausible',
  'pliable',
  'plumb',
  'politician',
  'polygamous',
  'poorest',
  'portmanteau',
  'posed',
  'positive',
  'possible',
  'postpartum',
  'prank',
  'pre-emptive',
  'precocious',
  'predicted',
  'premium',
  'preparatory',
  'prerequisite',
  'prescient',
  'preserved',
  'presidential',
  'pressed',
  'pressurized',
  'presumed',
  'prewar',
  'priced',
  'pricier',
  'primal',
  'primer',
  'primetime',
  'printed',
  'private',
  'problem',
  'procedural',
  'process',
  'prodigious',
  'professional',
  'programmed',
  'progressive',
  'prolific',
  'promising',
  'promulgated',
  'pronged',
  'proportionate',
  'protracted',
  'pulled',
  'pulsed',
  'purgatory',
  'quick',
  'rapid-fire',
  'raunchy',
  'razed',
  'reactive',
  'readable',
  'realizing',
  'recognised',
  'recovering',
  'recurrent',
  'recycled',
  'redeemable',
  'reflecting',
  'regal',
  'registering',
  'reliable',
  'reminiscent',
  'remorseless',
  'removable',
  'renewable',
  'repeating',
  'repellent',
  'reserve',
  'resigned',
  'respectful',
  'rested',
  'restrict',
  'resultant',
  'retaliatory',
  'retiring',
  'revelatory',
  'reverend',
  'reversing',
  'revolving',
  'ridiculous',
  'right-hand',
  'ringed',
  'risque',
  'robust',
  'roomful',
  'rotating',
  'roused',
  'rubber',
  'run-down',
  'running',
  'runtime',
  'rustling',
  'safest',
  'salient',
  'sanctioned',
  'saute',
  'saved',
  'scandalized',
  'scarlet',
  'scattering',
  'sceptical',
  'scheming',
  'scoundrel',
  'scratched',
  'scratchy',
  'scrolled',
  'seated',
  'second-best',
  'segregated',
  'self-taught',
  'semiautomatic',
  'senior',
  'sensed',
  'sentient',
  'sexier',
  'shadowy',
  'shaken',
  'shaker',
  'shameless',
  'shaped',
  'shiny',
  'shipped',
  'shivering',
  'shoestring',
  'short',
  'short-lived',
  'signed',
  'simplest',
  'simplistic',
  'sizable',
  'skeleton',
  'skinny',
  'skirting',
  'skyrocketed',
  'slamming',
  'slanting',
  'slapstick',
  'sleek',
  'sleepless',
  'sleepy',
  'slender',
  'slimmer',
  'smacking',
  'smokeless',
  'smothered',
  'smouldering',
  'snuff',
  'socialized',
  'solid-state',
  'sometime',
  'sought',
  'spanking',
  'sparing',
  'spattered',
  'specialized',
  'specific',
  'speedy',
  'spherical',
  'spiky',
  'spineless',
  'sprung',
  'squint',
  'stainless',
  'standing',
  'starlight',
  'startled',
  'stately',
  'statewide',
  'stereoscopic',
  'sticky',
  'stimulant',
  'stinky',
  'stoked',
  'stolen',
  'storied',
  'strained',
  'strapping',
  'strengthened',
  'stubborn',
  'stylized',
  'suave',
  'subjective',
  'subjugated',
  'subordinate',
  'succeeding',
  'suffering',
  'summary',
  'sunset',
  'sunshine',
  'supernatural',
  'supervisory',
  'supply-side',
  'surrogate',
  'suspended',
  'suspenseful',
  'swarthy',
  'sweating',
  'sweeping',
  'swinging',
  'swooning',
  'sympathize',
  'synchronized',
  'synonymous',
  'synthetic',
  'tailed',
  'tallest',
  'tangible',
  'tanked',
  'tarry',
  'technical',
  'tectonic',
  'telepathic',
  'tenderest',
  'territorial',
  'testimonial',
  'theistic',
  'thicker',
  'threatening',
  'tight-lipped',
  'timed',
  'timely',
  'timid',
  'torrent',
  'totalled',
  'tougher',
  'traditional',
  'transformed',
  'trapped',
  'traveled',
  'traverse',
  'treated',
  'trial',
  'trunk',
  'trusting',
  'trying',
  'twisted',
  'two-lane',
  'tyrannical',
  'unaided',
  'unassisted',
  'unassuming',
  'unattractive',
  'uncapped',
  'uncomfortable',
  'uncontrolled',
  'uncooked',
  'uncooperative',
  'underground',
  'undersea',
  'undisturbed',
  'unearthly',
  'uneasy',
  'unequal',
  'unfazed',
  'unfinished',
  'unforeseen',
  'unforgivable',
  'unidentified',
  'unimaginative',
  'uninspired',
  'unintended',
  'uninvited',
  'universal',
  'unmasked',
  'unorthodox',
  'unparalleled',
  'unpleasant',
  'unprincipled',
  'unread',
  'unreasonable',
  'unregulated',
  'unreliable',
  'unremitting',
  'unsafe',
  'unsanitary',
  'unsealed',
  'unsuccessful',
  'unsupervised',
  'untimely',
  'unwary',
  'unwrapped',
  'uppity',
  'upstart',
  'useless',
  'utter',
  'valiant',
  'valid',
  'valued',
  'vanilla',
  'vaulting',
  'vaunted',
  'veering',
  'vegetative',
  'vented',
  'verbal',
  'verifying',
  'veritable',
  'versed',
  'vinyl',
  'virgin',
  'visceral',
  'visual',
  'voluptuous',
  'walk-on',
  'wanton',
  'warlike',
  'washed',
  'waterproof',
  'waved',
  'weakest',
  'well-bred',
  'well-chosen',
  'well-informed',
  'wetting',
  'wheeled',
  'whirlwind',
  'widen',
  'widening',
  'willful',
  'willing',
  'winnable',
  'winningest',
  'wireless',
  'wistful',
  'woeful',
  'wooded',
  'woodland',
  'wordless',
  'workable',
  'worldly',
  'worldwide',
  'worsted',
];
